name: Eventix
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  cached_network_image: ^3.3.0
  carousel_slider: ^4.2.1
  dotted_decoration: ^2.0.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  flutter_login_facebook: ^1.6.2
  flutter_staggered_grid_view: ^0.4.1
  flutter_svg: ^1.1.6
  flutter_svg_provider: ^1.0.3
  flutter_switch: ^0.3.2
  get: ^4.6.5
  google_maps_flutter: ^2.2.2
  google_sign_in: ^5.0.7
  images_picker: ^1.2.11
  intl: ^0.17.0
  permission_handler: ^10.0.0
  pin_code_fields: ^7.3.0
  readmore: ^2.2.0
  shared_preferences: ^2.0.15
  smooth_page_indicator: ^1.0.0+2
  sms_autofill: ^2.0.0
  # sqflite package
  sqflite: ^2.3.3+1
  # flutter path provider
  path_provider: ^2.1.3
  # image picker
  image_picker: ^1.1.1
  fluttertoast: ^8.2.5
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/thumb.png"
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/OutfitSemiBold.ttf
          weight: 600
        - asset: assets/fonts/OutfitMedium.ttf
          weight: 500
        - asset: assets/fonts/OutfitLight.ttf
          weight: 300
        - asset: assets/fonts/OutfitRegular.ttf
          weight: 400
    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoRegular.ttf
          weight: 400
